output "instance_id" {
  description = "ID of the EC2 instance."
  value       = aws_instance.web.id
}

output "instance_arn" {
  description = "ARN of the EC2 instance."
  value       = aws_instance.web.arn
}

output "private_ip" {
  description = "Private IP assigned to the application EC2 instance."
  value       = aws_instance.web.private_ip
}

output "security_group_id" {
  description = "ID of the application EC2 security group."
  value       = aws_security_group.app.id
}

output "instance_role_arn" {
  description = "ARN of the IAM role attached to the EC2 instance."
  value       = aws_iam_role.ec2.arn
}

output "alb_dns_name" {
  description = "DNS name generated by the Application Load Balancer."
  value       = aws_lb.app.dns_name
}

output "application_url" {
  description = "Public HTTPS URL of the application."
  value       = "https://${var.domain_name}"
}

output "certificate_arn" {
  description = "ARN of the validated ACM certificate."
  value       = aws_acm_certificate_validation.app.certificate_arn
}
